on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: jasonaviandres/trello-github-branch-action@v1
        with:
          who-to-greet: "Jason"
